ITEMS_TO_EXTRACT: dict[str, str] = {
    "person_name": "",
    "person_name_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "social_role": "job/status, Eg. irtolainen, vaimo, torpparin veli",
    "social_role_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "age": "Age in years. If a reasonable guess can be made based on context provide the estimation with '~' prefix, Eg. '~17'",
    "age_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "men_count": "",
    "men_count_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "women_count": "",
    "women_count_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "parish_from": "The parish should be stored as-is from the source book without any modifications.",
    "parish_from_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "parish_to": "The parish should be stored as-is from the source book without any modifications.",
    "parish_to_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "date_original": "",
    "date_original_cells": 'What table cells the data was extracted from. Eg. "[(2, 4), (3, 4), ...]"',
    "date_yyyy-mm-dd": "YYYY-MM-DD formatted date. Replace uncertain characters with X.",
}
